/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

/**
 *
 * @author ale
 */
public class CategoriasTab extends javax.swing.JPanel {
    
    /*
     * TODO - DISEÑO INTERFAZ CATEGORÍAS:
     * - JList o JTable para mostrar categorías (nombre, descripción)
     * - JTextField para filtro por nombre
     * - JButton "Buscar" para aplicar filtro
     * - JButton "Reset (❌)" para mostrar todas las categorías
     * - Sidebar derecho con filtros siempre visible
     * 
     * TODO - FUNCIONALIDAD:
     * - Cargar categorías con CategoriaController.buscarTodos()
     * - Filtrar con CategoriaController.buscarPorNombre() al hacer clic "Buscar"
     * - Al hacer clic en una categoría: parent.irAJuegosDeCategoria(categoria)
     * - Reset vuelve al estado original (todas las categorías)
     * - Doble clic en categoría también navega a videojuegos
     */
    
    private MainFrame parent;
    private boolean modoAdmin = false;
    
    /**
     * Creates new form CategoriasTab
     */
    public CategoriasTab() {
        initComponents();
    }
    
    /**
     * Constructor con referencia al MainFrame padre
     */
    public CategoriasTab(MainFrame parent) {
        this();
        this.parent = parent;
        this.modoAdmin = parent.isModoAdmin();
    }
    
    /**
     * Actualiza el estado del modo administrador
     */
    public void actualizarModoAdmin(boolean modoAdmin) {
        this.modoAdmin = modoAdmin;
        // TODO: agregar la lógica para mostrar/ocultar botones
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
