/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

/**
 *
 * @author ale
 */
public class CrudTab extends javax.swing.JPanel {

    /*
     * TODO - DISEÑO INTERFAZ CRUD (SOLO VISIBLE EN MODO ADMIN):
     * - JTabbedPane interno con 4 pestañas:
     *   * "Categorías CRUD"
     *   * "Videojuegos CRUD" 
     *   * "Usuarios CRUD"
     *   * "Reseñas CRUD"
     * 
     * TODO - CADA PESTAÑA INTERNA DEBE TENER:
     * - JTable para mostrar datos existentes
     * - Formulario de creación/edición con campos apropiados
     * - JButton "Crear" para agregar nueva entidad
     * - JButton "Actualizar" para modificar entidad seleccionada
     * - JButton "Eliminar" para borrar entidad seleccionada
     * - Validaciones de campos requeridos
     * 
     * TODO - FUNCIONALIDAD POR ENTIDAD:
     * - Categorías: CategoriaController (crear, actualizar, eliminar, buscarTodos)
     * - Videojuegos: VideojuegoController (crear, actualizar, eliminar, buscarTodos)
     * - Usuarios: UsuarioController (crear, actualizar, eliminar, buscarTodos)
     * - Reseñas: ReseñaController (crear, actualizar, eliminar, buscarTodos)
     * - Refrescar tabla después de cada operación CRUD
     * - Mostrar mensajes de éxito/error
     */

    private MainFrame parent;

    /**
     * Creates new form CrudTab
     */
    public CrudTab() {
        initComponents();
    }
    
    /**
     * Constructor con referencia al MainFrame padre
     */
    public CrudTab(MainFrame parent) {
        this();
        this.parent = parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
