/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

/**
 *
 * @author ale
 */
public class JuegosTab extends javax.swing.JPanel {
    
    /*
     * TODO - DISEÑO INTERFAZ VIDEOJUEGOS:
     * - JList o JTable para mostrar videojuegos (título, año, categoría, puntuación promedio)
     * - Sidebar derecho con filtros:
     *   * JTextField para filtro por título
     *   * JComboBox para filtro por categoría
     *   * JSpinner para filtro por año
     * - JComboBox de ordenamiento (título, año, puntuación promedio)
     * - JButton "Buscar" para aplicar filtros
     * - JButton "Reset (❌)" para mostrar todos los videojuegos
     * 
     * TODO - FUNCIONALIDAD:
     * - Cargar videojuegos con VideojuegoController.buscarTodos()
     * - Filtrar por título: VideojuegoController.buscarPorTitulo()
     * - Filtrar por categoría: VideojuegoController.buscarPorCategoria()
     * - Filtrar por año: VideojuegoController.buscarPorAño()
     * - Al hacer clic en videojuego: parent.irAReseñasDeJuego(videojuego)
     * - Implementar filtrarPorCategoria() para navegación desde CategoriasTab
     * - Ordenamiento local de la lista mostrada
     */
    
    private MainFrame parent;
    
    /**
     * Creates new form VideojuegosTab
     */
    public JuegosTab() {
        initComponents();
        
    }
    
    /**
     * Constructor con referencia al MainFrame padre
     */
    public JuegosTab(MainFrame parent) {
        this();
        this.parent = parent;
    }
    
    /**
     * Filtrar videojuegos por categoría específica
     */
    public void filtrarPorCategoria(models.Categoria categoria) {
        // TODO: Implementar filtrado por categoría
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        jLabel1.setText("Buenos dias");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(166, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(160, 160, 160))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel1)
                .addContainerGap(209, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
