/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

/**
 *
 * @author ale
 */
public class PublicarTab extends javax.swing.JPanel {

    /*
     * TODO - DISEÑO INTERFAZ PUBLICAR RESEÑAS:
     * - ComboBox de videojuegos (cargar con VideojuegoController.buscarTodos())
     * - Slider de puntuación (1-10) con JLabel que muestre valor actual
     * - JTextArea para comentario de la reseña (con scroll)
     * - JCheckBox "Contiene spoilers"
     * - JButton "Publicar Reseña"
     * 
     * TODO - FUNCIONALIDAD:
     * - Al hacer clic "Publicar": crear nueva Reseña con usuario logueado
     * - Validar que se haya seleccionado videojuego y escrito comentario
     * - Usar ReseñaController.crear() para guardar en BD
     * - Mostrar mensaje de éxito/error
     * - Limpiar formulario después de publicar
     */

    private MainFrame parent;

    /**
     * Creates new form PublicartAB
     */
    public PublicarTab() {
        initComponents();
    }
    
    /**
     * Constructor con referencia al MainFrame padre
     */
    public PublicarTab(MainFrame parent) {
        this();
        this.parent = parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
