/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

/**
 *
 * @author ale
 */
public class ReseñasTab extends javax.swing.JPanel {
    
    /*
     * TODO - DISEÑO INTERFAZ RESEÑAS (CENTRO DE VISUALIZACIÓN):
     * - JList o JTable para mostrar reseñas (videojuego, usuario, puntuación, comentario, útiles)
     * - Sidebar derecho con filtros múltiples:
     *   * JComboBox para filtro por videojuego
     *   * JComboBox para filtro por usuario
     *   * JSpinner para puntuación mínima
     *   * JCheckBox "Mostrar spoilers" (usar parent.isMostrarSpoilers())
     * - JComboBox de ordenamiento (fecha, útiles, puntuación)
     * - JButton "Buscar" para aplicar filtros
     * - JButton "Reset (❌)" para mostrar todas las reseñas
     * - JButton "👍 Útil" en cada reseña para dar upvote
     * 
     * TODO - FUNCIONALIDAD:
     * - Cargar reseñas con ReseñaController.buscarTodos()
     * - Filtros: ReseñaController.buscarPorVideojuego(), buscarPorUsuario(), etc.
     * - Implementar mostrarReseñasDeJuego() para navegación desde JuegosTab
     * - Implementar mostrarReseñasDeUsuario() para navegación desde UsuariosTab
     * - Upvotes: ReseñaController.marcarComoUtil()
     * - Filtro spoilers: ocultar reseñas con spoilers si parent.isMostrarSpoilers() == false
     * - Ordenamiento local de la lista mostrada
     */
    
    private MainFrame parent;
    
    /**
     * Creates new form ReseñasTab
     */
    public ReseñasTab() {
        initComponents();
    }
    
    /**
     * Constructor con referencia al MainFrame padre
     */
    public ReseñasTab(MainFrame parent) {
        this();
        this.parent = parent;
    }
    
    /**
     * Mostrar reseñas de un videojuego específico
     */
    public void mostrarReseñasDeJuego(models.Videojuego juego) {
        // TODO: Implementar filtrado por videojuego
    }
    
    /**
     * Mostrar reseñas de un usuario específico
     */
    public void mostrarReseñasDeUsuario(models.Usuario usuario) {
        // TODO: Implementar filtrado por usuario
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
