/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

/**
 *
 * @author ale
 */
public class UsuariosTab extends javax.swing.JPanel {

    /*
     * TODO - DISEÑO INTERFAZ USUARIOS:
     * - JList o JTable para mostrar usuarios (nombre, email, total reseñas)
     * - Sidebar derecho con filtros:
     *   * JTextField para filtro por nombre
     *   * JTextField para filtro por email
     * - JButton "Buscar" para aplicar filtros
     * - JButton "Reset (❌)" para mostrar todos los usuarios
     * 
     * TODO - FUNCIONALIDAD:
     * - Cargar usuarios con UsuarioController.buscarTodos()
     * - Filtrar por nombre: UsuarioController.buscarPorNombre()
     * - Filtrar por email: UsuarioController.buscarPorEmail()
     * - Al hacer clic en usuario: parent.irAReseñasDeUsuario(usuario)
     * - Mostrar estadísticas: total de reseñas por usuario
     * - Doble clic en usuario también navega a sus reseñas
     */

    private MainFrame parent;
    private boolean modoAdmin = false;

    /**
     * Creates new form UsuariosTab
     */
    public UsuariosTab() {
        initComponents();
    }
    
    /**
     * Constructor con referencia al MainFrame padre
     */
    public UsuariosTab(MainFrame parent) {
        this();
        this.parent = parent;
    }
    
    /**
     * Actualiza el estado del modo administrador
     */
    public void actualizarModoAdmin(boolean modoAdmin) {
        this.modoAdmin = modoAdmin;
        // TODO: agregar la lógica para mostrar/ocultar botones
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(245, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jButton1)
                .addContainerGap(194, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
