/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views.tabs;

import views.MainFrame;

/**
 *
 * @author ale
 */
public class AjustesTab extends javax.swing.JPanel {

    /*
     * TODO - DISEÑO INTERFAZ AJUSTES:
     * - Sección "Configuración":
     *   * JCheckBox "Modo Administrador" → parent.setModoAdmin(boolean)
     *   * JCheckBox "Mostrar Spoilers" → parent.setMostrarSpoilers(boolean)
     * - Sección "Información del Usuario":
     *   * JLabel con nombre del usuario logueado
     *   * JLabel con email del usuario logueado
     * - Sección "Estadísticas":
     *   * JLabel "Total de reseñas publicadas: X"
     *   * JLabel "Videojuego favorito: X" (más reseñado por el usuario)
     * - JButton "Cerrar Sesión" → System.exit(0) o volver a login
     * 
     * TODO - FUNCIONALIDAD:
     * - Inicializar checkboxes según estado actual del parent
     * - ActionPerformed en checkboxes para actualizar configuración
     * - Cargar estadísticas del usuario con ReseñaController
     * - Método actualizarEstadoComponentes() para sincronizar con MainFrame
     * - Confirmar antes de cerrar sesión con JOptionPane
     */

    private MainFrame parent;

    /**
     * Creates new form AjustesTab
     */
    public AjustesTab() {
        initComponents();
    }
    
    /**
     * Constructor con referencia al MainFrame padre
     */
    public AjustesTab(MainFrame parent) {
        this();
        this.parent = parent;
        buttonGroup1.add(rBtnModoAdmin);
        buttonGroup1.add(rBtnModoNormal);
        buttonGroup2.add(rBtnSpoilers);
        buttonGroup2.add(rBtnNoSpoilers);

        if (parent.isModoAdmin()) {
            rBtnModoAdmin.setSelected(true);
        } else {
            rBtnModoNormal.setSelected(true);
        }
        if (parent.isMostrarSpoilers()) {
            rBtnSpoilers.setSelected(true);
        } else {
            rBtnNoSpoilers.setSelected(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        rBtnNoSpoilers = new javax.swing.JRadioButton();
        rBtnSpoilers = new javax.swing.JRadioButton();
        rBtnModoAdmin = new javax.swing.JRadioButton();
        rBtnModoNormal = new javax.swing.JRadioButton();
        btnEnviar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setText("Quiere entrar en modo admin?");

        rBtnNoSpoilers.setText("Evitar Spoilers");

        rBtnSpoilers.setText("Ver Spoilers");

        rBtnModoAdmin.setText("Modo admin");

        rBtnModoNormal.setText("Modo normal");

        btnEnviar.setText("Aplicar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        jLabel3.setText("Pulse aplicar para hacer efectivos los cambios");

        jLabel1.setText("Quiere evitar Spoilers?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(rBtnNoSpoilers)
                            .addComponent(rBtnSpoilers))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rBtnModoNormal)
                            .addComponent(rBtnModoAdmin)
                            .addComponent(jLabel2))))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEnviar)
                .addGap(120, 120, 120))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rBtnNoSpoilers)
                    .addComponent(rBtnModoAdmin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rBtnSpoilers)
                    .addComponent(rBtnModoNormal))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(btnEnviar)
                .addContainerGap(117, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        parent.setModoAdmin(rBtnModoAdmin.isSelected());
        parent.setMostrarSpoilers(rBtnSpoilers.isSelected());
    }//GEN-LAST:event_btnEnviarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton rBtnModoAdmin;
    private javax.swing.JRadioButton rBtnModoNormal;
    private javax.swing.JRadioButton rBtnNoSpoilers;
    private javax.swing.JRadioButton rBtnSpoilers;
    // End of variables declaration//GEN-END:variables
}
